name: properties
version: 1.0.0+dev
description: A simple library to manage properties file (and something more) in Dart
repository: https://github.com/vaind/properties.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.0.0
  test: ^1.0.0